### ISSUE TITLE
Dumb question: where's the code?

### ISSUE THREAD

**Issue by archiecobbs** [YugeshN/cockroach-java#1]
I see a LICENSE and a README.

Is there actual code somewhere?

**Comment by YugeshN** [comment]
Unfortunately CockroachDB are planning on removing (or may have already done so) their K/V API and are only making available a SQL interface.
That essentially nullified the work I was doing, so I stopped working on it.
I should probably delete the Repo. 

    On Thursday, February 11, 2016 1:02 PM, Archie L. Cobbs <notifications@github.com> wrote:
 

 I see a LICENSE and a README.Is there actual code somewhere?—
